services:
    frontend:
        build:
            context: ./client
        ports:
            - '3000:3000'
        environment:
            NEXT_PUBLIC_API_BASE_URL: https://localhost:8000
        volumes:
            - ./client/package.json:/client/package.json
            - ./client/node_modules:/client/node_modules
        command:
            - /bin/sh
            - -c
            - |
                echo "Starting client..."
                npx prisma generate
                npm run dev
        develop:
            watch:
                - action: sync
                  path: ./client/src/
                  target: /client/src
                - action: sync
                  path: ./client/public/
                  target: /client/public
                - action: sync
                  path: ./client/package.json
                  target: /client/package.json
                - action: sync
                  path: ./client/tailwind.config.ts
                  target: /client/tailwind.config.ts

    # springboot:
    #     build:
    #         context: ./server
    #     ports:
    #         - '8080:8080'
    #     environment:
    #         - SPRING_PROFILES_ACTIVE=dev
    #     volumes:
    #         - ./server:/server
    #         - ./server/pom.xml:/server/pom.xml
    #         - ./server/.mvn:/server/.mvn
    #         - ./server/mvnw:/server/mvnw
    #         - ~/.m2:/root/.m2
    # develop:
    #     watch:
    #         - action: sync
    #           path: ./server/
    #           target: /server/
    #           ignore:
    #               - .*.tmp
    #               - .*.class
