import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} h-screen w-screen flex flex-row p-4`}>
				<div className='w-1/6 h-full'>
					<Navbar></Navbar>
				</div>
				<div className='w-5/6 h-full'> {children}</div>
			</body>
		</html>
	);
}
